//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IosServiceAPp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHouse
    {
        public int houseid { get; set; }
        public string housename { get; set; }
        public string housepic { get; set; }
        public string housedetails { get; set; }
        public string city { get; set; }
    }
}
